import { Button, Form } from 'antd';
import { Input } from 'antd';
import React, { useState } from 'react';
import { CSVLink } from 'react-csv';
import FormGrid from '../../../components/FormGrid';

const TextArea = Input.TextArea;

const headers = [
  { label: '模版id', key: 'templateId' },
  { label: '模版名称', key: 'name' },
  { label: '所属应用', key: 'appName' },
  { label: '关联页面', key: 'pageName' },
  { label: '模版文件id', key: 'templateFileId' },
];

const data = [
  {
    "templateId": 2000103325,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_青海省本级",
    "defaultTemplateFile": "委托单模版_青海省本级.html",
    "templateFileId": 2000104267,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1713495623000,
    "synTime": 1713495623000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 664,
    "viewName": "委托单模版_青海省本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103318,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_ 和田市(和阗市)",
    "defaultTemplateFile": "委托单模版_ 和田市(和阗市).html",
    "templateFileId": 2000104265,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1712558465000,
    "synTime": 1712558465000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 657,
    "viewName": "委托单模版_ 和田市(和阗市)",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103710,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_云环境_大连阳光采购",
    "defaultTemplateFile": "委托单模板_云环境_大连阳光采购.html",
    "templateFileId": 2000104263,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1712498920000,
    "synTime": 1712498920000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 3030,
    "viewName": "委托单模板_大连阳光采购",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103702,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_财通_2023",
    "defaultTemplateFile": "委托单模板_财通_2023.html",
    "templateFileId": 2000104244,
    "statusName": "草稿",
    "status": 1,
    "updateTime": 1709208676000,
    "synTime": null,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": true
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 2082,
    "viewName": "委托单模板_财通_2023",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103296,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_平台默认",
    "defaultTemplateFile": "委托单模板_平台默认.html",
    "templateFileId": 2000104233,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1706496128000,
    "synTime": 1706496128000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 548,
    "viewName": "委托单模板_平台默认",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103313,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_伊犁哈萨克自治州巩留县",
    "defaultTemplateFile": "委托单模版_伊犁哈萨克自治州巩留县.html",
    "templateFileId": 2000104224,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1705290632000,
    "synTime": 1705290632000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 652,
    "viewName": "委托单模版_伊犁哈萨克自治州巩留县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103676,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "真线测试模版-999900",
    "defaultTemplateFile": "真线测试模版-999900.html",
    "templateFileId": 2000104223,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1705290536000,
    "synTime": 1705290536000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 2870,
    "viewName": "真线测试模版-999900",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103653,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_新疆烟草",
    "defaultTemplateFile": "委托单模版_新疆烟草.html",
    "templateFileId": 2000104112,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1698752616000,
    "synTime": 1698752616000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 2624,
    "viewName": "委托单模版_新疆烟草",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103307,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_永康市",
    "defaultTemplateFile": "委托单模版_永康市.html",
    "templateFileId": 2000104085,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1694759670000,
    "synTime": 1694759670000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 646,
    "viewName": "委托单模版_永康市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103336,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_测试省本级",
    "defaultTemplateFile": "委托单模版_测试省本级.html",
    "templateFileId": 2000104063,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1693482359000,
    "synTime": 1693482359000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 676,
    "viewName": "委托单模版_测试省本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103350,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_新疆维吾尔自治区本级",
    "defaultTemplateFile": "委托单模版_新疆维吾尔自治区本级.html",
    "templateFileId": 2000104060,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1693478667000,
    "synTime": 1693478667000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 754,
    "viewName": "委托单模版_新疆维吾尔自治区本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103383,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_江南区",
    "defaultTemplateFile": "委托单模版_江南区.html",
    "templateFileId": 2000103988,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716834000,
    "synTime": 1688716834000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 787,
    "viewName": "委托单模版_江南区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103364,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_田东县",
    "defaultTemplateFile": "委托单模版_田东县.html",
    "templateFileId": 2000103986,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716803000,
    "synTime": 1688716803000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 768,
    "viewName": "委托单模版_田东县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103358,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_隆林各族自治县",
    "defaultTemplateFile": "委托单模版_隆林各族自治县.html",
    "templateFileId": 2000103984,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716655000,
    "synTime": 1688716655000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 762,
    "viewName": "委托单模版_隆林各族自治县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103378,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_天等县",
    "defaultTemplateFile": "委托单模版_天等县.html",
    "templateFileId": 2000103983,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716625000,
    "synTime": 1688716625000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 782,
    "viewName": "委托单模版_天等县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103390,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_灵川县",
    "defaultTemplateFile": "委托单模版_灵川县.html",
    "templateFileId": 2000103980,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716444000,
    "synTime": 1688716444000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 794,
    "viewName": "委托单模版_灵川县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103317,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_南宁市马山县",
    "defaultTemplateFile": "委托单模版_南宁市马山县.html",
    "templateFileId": 2000103977,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716206000,
    "synTime": 1688716206000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 656,
    "viewName": "委托单模版_南宁市马山县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103387,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_恭城瑶族自治县",
    "defaultTemplateFile": "委托单模版_恭城瑶族自治县.html",
    "templateFileId": 2000103975,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688716052000,
    "synTime": 1688716052000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 791,
    "viewName": "委托单模版_恭城瑶族自治县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103363,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_凌云县",
    "defaultTemplateFile": "委托单模版_凌云县.html",
    "templateFileId": 2000103973,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688715952000,
    "synTime": 1688715952000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 767,
    "viewName": "委托单模版_凌云县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103326,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_广西壮族自治区本级",
    "defaultTemplateFile": "委托单模版_广西壮族自治区本级.html",
    "templateFileId": 2000103971,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688715685000,
    "synTime": 1688715685000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 665,
    "viewName": "委托单模版_广西壮族自治区本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103377,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_扶绥县",
    "defaultTemplateFile": "委托单模版_扶绥县.html",
    "templateFileId": 2000103970,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688715560000,
    "synTime": 1688715560000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 781,
    "viewName": "委托单模版_扶绥县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103328,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_北海市本级",
    "defaultTemplateFile": "委托单模版_北海市本级.html",
    "templateFileId": 2000103969,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688715523000,
    "synTime": 1688715523000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 667,
    "viewName": "委托单模版_北海市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103375,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_龙州县",
    "defaultTemplateFile": "委托单模版_龙州县.html",
    "templateFileId": 2000103966,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688715152000,
    "synTime": 1688715152000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 779,
    "viewName": "委托单模版_龙州县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103332,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_南宁市本级",
    "defaultTemplateFile": "委托单模版_南宁市本级.html",
    "templateFileId": 2000103963,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688714913000,
    "synTime": 1688714913000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 671,
    "viewName": "委托单模版_南宁市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103359,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_右江区",
    "defaultTemplateFile": "委托单模版_右江区.html",
    "templateFileId": 2000103962,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688714874000,
    "synTime": 1688714874000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 763,
    "viewName": "委托单模版_右江区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103322,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_河池市东兰县",
    "defaultTemplateFile": "委托单模版_河池市东兰县.html",
    "templateFileId": 2000103960,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688714642000,
    "synTime": 1688714642000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 661,
    "viewName": "委托单模版_河池市东兰县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103392,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_临桂区",
    "defaultTemplateFile": "委托单模版_临桂区.html",
    "templateFileId": 2000103959,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688714491000,
    "synTime": 1688714491000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 796,
    "viewName": "委托单模版_临桂区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103368,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_南宁高新技术产业开发区",
    "defaultTemplateFile": "委托单模版_南宁高新技术产业开发区.html",
    "templateFileId": 2000103958,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688714443000,
    "synTime": 1688714443000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 772,
    "viewName": "委托单模版_南宁高新技术产业开发区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103360,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_靖西市",
    "defaultTemplateFile": "委托单模版_靖西市.html",
    "templateFileId": 2000103955,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688714135000,
    "synTime": 1688714135000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 764,
    "viewName": "委托单模版_靖西市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103366,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_桂林市本级",
    "defaultTemplateFile": "委托单模版_桂林市本级.html",
    "templateFileId": 2000103953,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688713951000,
    "synTime": 1688713951000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 770,
    "viewName": "委托单模版_桂林市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103389,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_防城区",
    "defaultTemplateFile": "委托单模版_防城区.html",
    "templateFileId": 2000103951,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688713680000,
    "synTime": 1688713680000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 793,
    "viewName": "委托单模版_防城区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103382,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_城中区",
    "defaultTemplateFile": "委托单模版_城中区.html",
    "templateFileId": 2000103950,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688713627000,
    "synTime": 1688713627000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 786,
    "viewName": "委托单模版_城中区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103356,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_防城港市本级",
    "defaultTemplateFile": "委托单模版_防城港市本级.html",
    "templateFileId": 2000103948,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688713099000,
    "synTime": 1688713099000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 760,
    "viewName": "委托单模版_防城港市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103362,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_上思县",
    "defaultTemplateFile": "委托单模版_上思县.html",
    "templateFileId": 2000103947,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688713071000,
    "synTime": 1688713071000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 766,
    "viewName": "委托单模版_上思县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103369,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_南宁青秀山风景名胜旅游区",
    "defaultTemplateFile": "委托单模版_南宁青秀山风景名胜旅游区.html",
    "templateFileId": 2000103944,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688712606000,
    "synTime": 1688712606000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 773,
    "viewName": "委托单模版_南宁青秀山风景名胜旅游区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103312,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_北海市海城区",
    "defaultTemplateFile": "委托单模版_北海市海城区.html",
    "templateFileId": 2000103943,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688712476000,
    "synTime": 1688712476000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 651,
    "viewName": "委托单模版_北海市海城区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103385,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_阳朔县",
    "defaultTemplateFile": "委托单模版_阳朔县.html",
    "templateFileId": 2000103942,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688712178000,
    "synTime": 1688712178000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 789,
    "viewName": "委托单模版_阳朔县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103367,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_钦州市本级",
    "defaultTemplateFile": "委托单模版_钦州市本级.html",
    "templateFileId": 2000103941,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688711957000,
    "synTime": 1688711957000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 771,
    "viewName": "委托单模版_钦州市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103376,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_宁明县",
    "defaultTemplateFile": "委托单模版_宁明县.html",
    "templateFileId": 2000103940,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688711795000,
    "synTime": 1688711795000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 780,
    "viewName": "委托单模版_宁明县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103373,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_梧州市本级",
    "defaultTemplateFile": "委托单模版_梧州市本级.html",
    "templateFileId": 2000103939,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688711707000,
    "synTime": 1688711707000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 777,
    "viewName": "委托单模版_梧州市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103393,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_东兴市",
    "defaultTemplateFile": "委托单模版_东兴市.html",
    "templateFileId": 2000103938,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688711123000,
    "synTime": 1688711123000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 797,
    "viewName": "委托单模版_东兴市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103391,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_河池市本级",
    "defaultTemplateFile": "委托单模版_河池市本级.html",
    "templateFileId": 2000103929,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1688636896000,
    "synTime": 1688636896000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 795,
    "viewName": "委托单模版_河池市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103603,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单-交投",
    "defaultTemplateFile": "委托单-交投.html",
    "templateFileId": 2000103899,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1687760447000,
    "synTime": 1687760447000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 2267,
    "viewName": "委托单模板_交投",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103395,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_浙江默认",
    "defaultTemplateFile": "委托单模板_浙江默认.html",
    "templateFileId": 2000103892,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1687173839000,
    "synTime": 1687173839000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 880,
    "viewName": "委托单模板_浙江默认",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103581,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_金控",
    "defaultTemplateFile": "委托单模板_金控.html",
    "templateFileId": 2000103872,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1682601468000,
    "synTime": null,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 1992,
    "viewName": "委托单模板_金控",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103357,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_缙云县",
    "defaultTemplateFile": "委托单模版_缙云县.html",
    "templateFileId": 2000103388,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680162198000,
    "synTime": 1680162198000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 761,
    "viewName": "委托单模版_缙云县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103344,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_杭州市萧山区",
    "defaultTemplateFile": "委托单模版_杭州市萧山区.html",
    "templateFileId": 2000103375,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680162115000,
    "synTime": 1680162115000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 707,
    "viewName": "委托单模版_杭州市萧山区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103372,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_岱山县",
    "defaultTemplateFile": "委托单模版_岱山县.html",
    "templateFileId": 2000103403,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680162081000,
    "synTime": 1680162081000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 776,
    "viewName": "委托单模版_岱山县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103371,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_衢江区",
    "defaultTemplateFile": "委托单模版_衢江区.html",
    "templateFileId": 2000103402,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161978000,
    "synTime": 1680161978000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 775,
    "viewName": "委托单模版_衢江区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103370,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_开化县",
    "defaultTemplateFile": "委托单模版_开化县.html",
    "templateFileId": 2000103401,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161956000,
    "synTime": 1680161956000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 774,
    "viewName": "委托单模版_开化县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103298,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_浙江省采",
    "defaultTemplateFile": "委托单模板_浙江省采.html",
    "templateFileId": 2000103329,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161888000,
    "synTime": 1680161888000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 615,
    "viewName": "委托单模板_浙江省采",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103361,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_衢州市本级",
    "defaultTemplateFile": "委托单模版_衢州市本级.html",
    "templateFileId": 2000103392,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161639000,
    "synTime": 1680161639000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 765,
    "viewName": "委托单模版_衢州市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103365,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_丽水市本级",
    "defaultTemplateFile": "委托单模版_丽水市本级.html",
    "templateFileId": 2000103396,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161366000,
    "synTime": 1680161366000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 769,
    "viewName": "委托单模版_丽水市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103386,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_湖州市本级",
    "defaultTemplateFile": "委托单模版_湖州市本级.html",
    "templateFileId": 2000103417,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161256000,
    "synTime": 1680161256000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 790,
    "viewName": "委托单模版_湖州市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103388,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_临平区",
    "defaultTemplateFile": "委托单模版_临平区.html",
    "templateFileId": 2000103419,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161217000,
    "synTime": 1680161217000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 792,
    "viewName": "委托单模版_杭州市临平区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103379,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_海宁市",
    "defaultTemplateFile": "委托单模版_海宁市.html",
    "templateFileId": 2000103410,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161116000,
    "synTime": 1680161116000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 783,
    "viewName": "委托单模版_海宁市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103380,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_台州市本级",
    "defaultTemplateFile": "委托单模版_台州市本级.html",
    "templateFileId": 2000103411,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161093000,
    "synTime": 1680161093000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 784,
    "viewName": "委托单模版_台州市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103396,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_宁波鄞州区",
    "defaultTemplateFile": "委托单模板_宁波鄞州区.html",
    "templateFileId": 2000103427,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161042000,
    "synTime": 1680161042000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 1127,
    "viewName": "委托单模板_宁波鄞州区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103304,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_瑞安市",
    "defaultTemplateFile": "委托单模版_瑞安市.html",
    "templateFileId": 2000103335,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680161019000,
    "synTime": 1680161019000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 643,
    "viewName": "委托单模版_瑞安市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103305,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_余姚市",
    "defaultTemplateFile": "委托单模版_余姚市.html",
    "templateFileId": 2000103336,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160996000,
    "synTime": 1680160996000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 644,
    "viewName": "委托单模版_余姚市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103306,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_温州市文成县",
    "defaultTemplateFile": "委托单模版_温州市文成县.html",
    "templateFileId": 2000103337,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160965000,
    "synTime": 1680160965000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 645,
    "viewName": "委托单模版_温州市文成县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103308,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_丽水市庆元县",
    "defaultTemplateFile": "委托单模版_丽水市庆元县.html",
    "templateFileId": 2000103339,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160947000,
    "synTime": 1680160947000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 647,
    "viewName": "委托单模版_丽水市庆元县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103309,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_台州市仙居县",
    "defaultTemplateFile": "委托单模版_台州市仙居县.html",
    "templateFileId": 2000103340,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160912000,
    "synTime": 1680160912000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 648,
    "viewName": "委托单模版_台州市仙居县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103299,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_成都",
    "defaultTemplateFile": "委托单模板_成都.html",
    "templateFileId": 2000103330,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160885000,
    "synTime": 1680160885000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 616,
    "viewName": "委托单模板_成都",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103301,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_宁波市北仑区",
    "defaultTemplateFile": "委托单模版_宁波市北仑区.html",
    "templateFileId": 2000103332,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160864000,
    "synTime": 1680160864000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 640,
    "viewName": "委托单模版_宁波市北仑区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103303,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_杭州市拱墅区",
    "defaultTemplateFile": "委托单模版_杭州市拱墅区.html",
    "templateFileId": 2000103334,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160843000,
    "synTime": 1680160843000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 642,
    "viewName": "委托单模版_原杭州市拱墅区_已停用",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103323,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_台州市 黄岩区",
    "defaultTemplateFile": "委托单模版_台州市 黄岩区.html",
    "templateFileId": 2000103354,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160745000,
    "synTime": 1680160745000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 662,
    "viewName": "委托单模版_台州市 黄岩区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103315,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_杭州市西湖区",
    "defaultTemplateFile": "委托单模版_杭州市西湖区.html",
    "templateFileId": 2000103346,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160724000,
    "synTime": 1680160724000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 654,
    "viewName": "委托单模版_杭州市西湖区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103319,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_重庆市九龙坡区",
    "defaultTemplateFile": "委托单模版_重庆市九龙坡区.html",
    "templateFileId": 2000103350,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160703000,
    "synTime": 1680160703000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 658,
    "viewName": "委托单模版_重庆市九龙坡区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103338,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_乐山市本级",
    "defaultTemplateFile": "委托单模版_乐山市本级.html",
    "templateFileId": 2000103369,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160630000,
    "synTime": 1680160630000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 678,
    "viewName": "委托单模版_乐山市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103339,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_电子交易专区",
    "defaultTemplateFile": "委托单模版_电子交易专区.html",
    "templateFileId": 2000103370,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160604000,
    "synTime": 1680160604000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 679,
    "viewName": "委托单模版_电子交易专区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103340,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_塔城地区本级",
    "defaultTemplateFile": "委托单模版_塔城地区本级.html",
    "templateFileId": 2000103371,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160581000,
    "synTime": 1680160581000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 680,
    "viewName": "委托单模版_塔城地区本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103342,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_成培县",
    "defaultTemplateFile": "委托单模版_成培县.html",
    "templateFileId": 2000103373,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160559000,
    "synTime": 1680160559000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 682,
    "viewName": "委托单模版_成培县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103311,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_霍尔果斯市",
    "defaultTemplateFile": "委托单模版_霍尔果斯市.html",
    "templateFileId": 2000103342,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160504000,
    "synTime": 1680160504000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 650,
    "viewName": "委托单模版_霍尔果斯市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103381,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_和静县",
    "defaultTemplateFile": "委托单模版_和静县.html",
    "templateFileId": 2000103412,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160477000,
    "synTime": 1680160477000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 785,
    "viewName": "委托单模版_和静县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103330,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_国家体育总局",
    "defaultTemplateFile": "委托单模版_国家体育总局.html",
    "templateFileId": 2000103361,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160413000,
    "synTime": 1680160413000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 669,
    "viewName": "委托单模版_国家体育总局",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103302,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_杭州市本级",
    "defaultTemplateFile": "委托单模版_杭州市本级.html",
    "templateFileId": 2000103333,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160360000,
    "synTime": 1680160360000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 641,
    "viewName": "委托单模版_杭州市本级_拱墅区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103300,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": " 委托单模版_诸暨市",
    "defaultTemplateFile": " 委托单模版_诸暨市.html",
    "templateFileId": 2000103331,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680160044000,
    "synTime": 1680160044000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 639,
    "viewName": " 委托单模版_诸暨市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103374,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_上虞区",
    "defaultTemplateFile": "委托单模版_上虞区.html",
    "templateFileId": 2000103405,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680159995000,
    "synTime": 1680159995000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 778,
    "viewName": "委托单模版_上虞区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103441,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_宁波慈溪市",
    "defaultTemplateFile": "委托单模板_宁波慈溪市.html",
    "templateFileId": 2000103474,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1680159909000,
    "synTime": 1680159909000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 1190,
    "viewName": "委托单模板_宁波慈溪市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103561,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "测试勿删",
    "defaultTemplateFile": "测试勿删.html",
    "templateFileId": 2000103760,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918230000,
    "synTime": 1679918230000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 1907,
    "viewName": "测试勿删",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103331,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_甲子县",
    "defaultTemplateFile": "委托单模版_甲子县.html",
    "templateFileId": 2000103791,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918180000,
    "synTime": 1679918180000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 670,
    "viewName": "委托单模版_甲子县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103352,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_临安区",
    "defaultTemplateFile": "委托单模版_临安区.html",
    "templateFileId": 2000103753,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918175000,
    "synTime": 1679918175000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 756,
    "viewName": "委托单模版_杭州市临安区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103354,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_皮山县",
    "defaultTemplateFile": "委托单模版_皮山县.html",
    "templateFileId": 2000103758,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918171000,
    "synTime": 1679918171000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 758,
    "viewName": "委托单模版_皮山县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103355,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_兵团本级",
    "defaultTemplateFile": "委托单模版_兵团本级.html",
    "templateFileId": 2000103706,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918168000,
    "synTime": 1679918168000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 759,
    "viewName": "委托单模版_兵团本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103348,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_钱塘新区",
    "defaultTemplateFile": "委托单模版_钱塘新区.html",
    "templateFileId": 2000103714,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918150000,
    "synTime": 1679918150000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 752,
    "viewName": "委托单模版_杭州市钱塘新区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103349,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_桐庐县",
    "defaultTemplateFile": "委托单模版_桐庐县.html",
    "templateFileId": 2000103747,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918147000,
    "synTime": 1679918147000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 753,
    "viewName": "委托单模版_杭州市桐庐县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103351,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_西湖风景名胜区",
    "defaultTemplateFile": "委托单模版_西湖风景名胜区.html",
    "templateFileId": 2000103750,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1679918141000,
    "synTime": 1679918141000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 755,
    "viewName": "委托单模版_杭州市西湖风景名胜区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103329,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_培训省本级",
    "defaultTemplateFile": "委托单模版_培训省本级.html",
    "templateFileId": 2000103675,
    "statusName": "已发布",
    "status": 2,
    "updateTime": 1678951362000,
    "synTime": 1678951362000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 668,
    "viewName": "委托单模版_培训省本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103297,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "历史数据兼容",
    "defaultTemplateFile": "历史数据兼容.html",
    "templateFileId": 2000103328,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 571,
    "viewName": "历史数据兼容",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103310,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_舟山市嵊泗县",
    "defaultTemplateFile": "委托单模版_舟山市嵊泗县.html",
    "templateFileId": 2000103341,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 649,
    "viewName": "委托单模版_舟山市嵊泗县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103314,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_宁波市宁海县",
    "defaultTemplateFile": "委托单模版_宁波市宁海县.html",
    "templateFileId": 2000103345,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 653,
    "viewName": "委托单模版_宁波市宁海县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103316,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_果洛藏族自治州达日县",
    "defaultTemplateFile": "委托单模版_果洛藏族自治州达日县.html",
    "templateFileId": 2000103347,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 655,
    "viewName": "委托单模版_果洛藏族自治州达日县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103320,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_喀什地区疏勒县",
    "defaultTemplateFile": "委托单模版_喀什地区疏勒县.html",
    "templateFileId": 2000103351,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 659,
    "viewName": "委托单模版_喀什地区疏勒县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103321,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_重庆市巴南区",
    "defaultTemplateFile": "委托单模版_重庆市巴南区.html",
    "templateFileId": 2000103352,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 660,
    "viewName": "委托单模版_重庆市巴南区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103324,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_重庆市丰都县(酆都县)",
    "defaultTemplateFile": "委托单模版_重庆市丰都县(酆都县).html",
    "templateFileId": 2000103355,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 663,
    "viewName": "委托单模版_重庆市丰都县(酆都县)",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103327,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_致远县",
    "defaultTemplateFile": "委托单模版_致远县.html",
    "templateFileId": 2000103358,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 666,
    "viewName": "委托单模版_致远县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103333,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_重庆市本级",
    "defaultTemplateFile": "委托单模版_重庆市本级.html",
    "templateFileId": 2000103364,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 672,
    "viewName": "委托单模版_重庆市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103334,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_南京市本级",
    "defaultTemplateFile": "委托单模版_南京市本级.html",
    "templateFileId": 2000103365,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 673,
    "viewName": "委托单模版_南京市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103335,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_测试省",
    "defaultTemplateFile": "委托单模版_测试省.html",
    "templateFileId": 2000103366,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 674,
    "viewName": "委托单模版_测试省",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103337,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_彩云市本级",
    "defaultTemplateFile": "委托单模版_彩云市本级.html",
    "templateFileId": 2000103368,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 677,
    "viewName": "委托单模版_彩云市本级",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103341,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_疆培县",
    "defaultTemplateFile": "委托单模版_疆培县.html",
    "templateFileId": 2000103372,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 681,
    "viewName": "委托单模版_疆培县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103343,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_无锡市",
    "defaultTemplateFile": "委托单模版_无锡市.html",
    "templateFileId": 2000103374,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 698,
    "viewName": "委托单模版_无锡市",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103345,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_无锡市政府采购中心",
    "defaultTemplateFile": "委托单模版_无锡市政府采购中心.html",
    "templateFileId": 2000103376,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 708,
    "viewName": "委托单模版_无锡市政府采购中心",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103346,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_无锡市培训省集采",
    "defaultTemplateFile": "委托单模版_无锡市培训省集采.html",
    "templateFileId": 2000103377,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 709,
    "viewName": "委托单模版_无锡市培训省集采",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103347,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模板_山西",
    "defaultTemplateFile": "委托单模板_山西.html",
    "templateFileId": 2000103378,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 723,
    "viewName": "委托单模板_山西",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103353,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_青培县",
    "defaultTemplateFile": "委托单模版_青培县.html",
    "templateFileId": 2000103384,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 757,
    "viewName": "委托单模版_青培县",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103384,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_沙湾区",
    "defaultTemplateFile": "委托单模版_沙湾区.html",
    "templateFileId": 2000103415,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 788,
    "viewName": "委托单模版_沙湾区",
    "isExistLayout": 1
  },
  {
    "templateId": 2000103394,
    "appId": 3019,
    "appName": "项目采购-委托中心",
    "pageId": 3086,
    "pageName": "委托单",
    "name": "委托单模版_培训省-演示A市-滇培县",
    "defaultTemplateFile": "委托单模版_培训省-演示A市-滇培县.html",
    "templateFileId": 2000103425,
    "statusName": "已同步",
    "status": 3,
    "updateTime": 1632821224000,
    "synTime": 1632821222000,
    "operateAuth": {
      "delete": true,
      "edit": true,
      "templateFile": true,
      "synTemplate": false,
      "publish": false
    },
    "specification": "",
    "fileExt": "html",
    "extraJson": "",
    "mockData": null,
    "viewId": 816,
    "viewName": "委托单模版_培训省-演示A市-滇培县",
    "isExistLayout": 1
  }
].map((item = {}) => {
  item.templateId += '';
  item.templateFileId += '';
  return item;
})

const formItemLayout = {
  labelCol: {
    xs: { span: 24 },
    sm: { span: 3 },
  },
  wrapperCol: {
    xs: { span: 24 },
    sm: { span: 21 },
  },
};

export default function ExportCsv(props) {
  const [form] = Form.useForm();
  const [initialValues, setValues] = useState({ data: JSON.stringify(data, null, 4), headers: JSON.stringify(headers, null, 4) });
  const handleClick = () => {
    console.log(form.getFieldsValue(), 'val')
    setValues(form.getFieldsValue());
  }

  return (
    <> 
      <FormGrid 
        form={form} 
        initialValues={initialValues}
        items={[
          { label: 'headers', field: 'headers', render: () => <TextArea rows={9} /> },
          { label: 'data', field: 'data', render: () => <TextArea rows={9} /> }
        ]}
      />
      <Button onClick={() => handleClick()}>click</Button>
      <br /> <br />


      <CSVLink data={JSON.parse(initialValues.data)} headers={JSON.parse(initialValues.headers)}>
        {props.children || 'Download me'}
      </CSVLink>
    </>
  );
}
